### ISSUE TITLE
Add Vectors for REV Components

### ISSUE THREAD

**Issue by marshallmassengill** [wpilibsuite/Control-System-Vectors#2]
:) https://www.revrobotics.com/blog/introducing-the-rev-development-blog/

I still love that this exists.  I toss these into Miro and it makes for a good virtual learning session for building out a robot's electrical system with the students.

**Comment by benjamin-antupit** [comment]
Hi @marshallmassengill! Glad to hear these are a helpful resource. 

I was a primary maintainer of the vector graphics for frc-docs and I haven't been keeping up with the new control system for 2022. I hope to create new graphics as documentation is developed, but that may be a while. In the meantime, anyone is free to work on it and submit a PR.

**Comment by marshallmassengill** [comment]
Would love to help but outside my wheel house.  Happy to wait for these but wanted to see if they were in the works and appreciate the work on the originals and the update for the future.

**Comment by Daltz333** [comment]
REV should be providing vectors in the upcoming weeks, with docs updated close to beta and hardware availability.

**Comment by mack-6326** [comment]
We have this on our radar as a to do item. This will get done at the same time as we start pushing out additional documentation on the control system components.

**Comment by marshallmassengill** [comment]
Resolved.  Thanks folks!
