### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by TheTripleV** [wpilibsuite/Control-System-Vectors#8]

**Comment by RishiKumarRay** [comment]
I would like to do this? can you assign me

**Comment by RishiKumarRay** [comment]
Can you tell me some brief about the installation process

**Comment by TheTripleV** [comment]
It's converting https://github.com/wpilibsuite/Control-System-Vectors/blob/main/azure-pipeline.yml into Github Actions syntax and turning it into a Github Action. It would go in `.github/workflows/ci.yaml`

**Comment by RishiKumarRay** [comment]
@Daltz333 @TheTripleV please review the PR #9 , I have attached the screenshot also of successful build
